# Generated by Django 6.0.2 on 2026-02-08 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, default="", verbose_name="О себе"),
                ),
                (
                    "github",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="GitHub"
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Twitter"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, default="", verbose_name="Сайт"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
            },
        ),
    ]
