# Generated by Django 6.0.2 on 2026-02-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100, verbose_name="Статья")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Адрес страницы"
                    ),
                ),
                ("content", models.TextField(verbose_name="Статья")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("published", "Опубликовано")],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
