# Generated by Django 6.0.2 on 2026-02-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="blog/images/",
                verbose_name="Изображение",
            ),
        ),
    ]
