# Generated by Django 6.0.2 on 2026-02-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_category_options_article_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Краткое описание статьи для превью",
                verbose_name="Описание",
            ),
        ),
    ]
